[simulation]
interaction_strength = 6.67430e-11
smoothing = 100.0
particle_radius = 0.0
timestep = 1.0
steps = 120
verification_enabled = true
verification_energy_max_particles = 2000
store_data = true
video_encoding_enabled = true
logging_enabled = true
fps = 1.0

[barnes_hut]
opening_angle = 0.5

[fmm]
expansion_order = 5
multipole_acceptance = 0.4
leaf_size = 20

[particles]
state_file = "fixed_state.bin"
